services:
  backend-dev:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development

  backend-prod:
    build:
      context: ./backend
      target: prod
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
  
  frontend-dev:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      # Exclude node_modules and .next
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development

  frontend-prod:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production