services:
  backend-dev:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/:/app
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      APP_ENV: "development"
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URL: ${GITHUB_REDIRECT_URL}
      GITHUB_INSTALLATION_ID: ${GITHUB_INSTALLATION_ID}
      GITHUB_PRIVATE_KEY: ${GITHUB_PRIVATE_KEY}

  backend-prod:
    build:
      context: ./backend
      target: prod
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      APP_ENV: "production"
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URL: ${GITHUB_REDIRECT_URL}
      GITHUB_INSTALLATION_ID: ${GITHUB_INSTALLATION_ID}
      GITHUB_PRIVATE_KEY: ${GITHUB_PRIVATE_KEY}
  
  frontend-dev:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development

  frontend-prod:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production